/**
 * The templates catalog — full pages and apps composed from cano components.
 * Two kinds: marketing "website" templates and interactive "saas" products.
 *
 * Adding a template = append an entry here, create the page component at
 * `templates/<slug>.tsx` (default export), and register it in
 * `templates/index.tsx`. The gallery, filters, and preview routes pick it up.
 */
export type TemplateKind = "website" | "saas"
export type TemplatePages = "single" | "multi"

export interface TemplateMeta {
  slug: string
  name: string
  description: string
  kind: TemplateKind
  /** Category slug — see CATEGORIES. */
  category: string
  pages: TemplatePages
  tags: string[]
  /** cano components the template is built from. */
  components: string[]
  /** Higher = newer; drives the "Newest" sort. */
  order: number
}

export interface Category {
  slug: string
  label: string
  kind: TemplateKind
}

export const CATEGORIES: Category[] = [
  // Website categories (≥20 templates each, single + multi-page).
  { slug: "marketing-landing", label: "Marketing & Landing", kind: "website" },
  { slug: "saas-software", label: "SaaS & Software", kind: "website" },
  { slug: "ecommerce", label: "E-commerce & Retail", kind: "website" },
  { slug: "startup-launch", label: "Startup & Product Launch", kind: "website" },
  { slug: "agency-studio", label: "Agency & Studio", kind: "website" },
  { slug: "portfolio", label: "Portfolio & Personal", kind: "website" },
  { slug: "blog-publishing", label: "Blog & Publishing", kind: "website" },
  { slug: "corporate", label: "Corporate & Business", kind: "website" },
  { slug: "events", label: "Events & Conferences", kind: "website" },
  { slug: "education", label: "Education & Community", kind: "website" },
  // SaaS product categories.
  { slug: "analytics", label: "Analytics", kind: "saas" },
  { slug: "crm", label: "CRM & Sales", kind: "saas" },
  { slug: "project", label: "Project Management", kind: "saas" },
  { slug: "finance", label: "Finance & Billing", kind: "saas" },
  { slug: "ai", label: "AI & Chat", kind: "saas" },
  { slug: "full-product", label: "Full Products", kind: "saas" },
]

export const CATEGORY_LABEL: Record<string, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c.label])
)

export const TEMPLATES: TemplateMeta[] = [
  {
    slug: "saas-landing",
    name: "SaaS Landing",
    description:
      "A conversion-focused SaaS landing page — hero, logos, features, metrics, pricing, testimonials, FAQ, and CTA.",
    kind: "website",
    category: "marketing-landing",
    pages: "single",
    tags: ["landing", "saas", "pricing", "marketing"],
    components: [
      "button",
      "badge",
      "card",
      "accordion",
      "stats-grid",
      "pricing-cards",
      "testimonial-cards",
    ],
    order: 2,
  },
  {
    slug: "analytics-dashboard",
    name: "Analytics Dashboard",
    description:
      "An interactive analytics dashboard with a range switcher, KPI cards, charts, a top-pages table, and an activity feed.",
    kind: "saas",
    category: "analytics",
    pages: "single",
    tags: ["dashboard", "analytics", "charts", "interactive"],
    components: [
      "app-shell",
      "stats-grid",
      "chart-cards",
      "data-table-pro",
      "activity-feed",
      "button-group",
      "tabs",
    ],
    order: 1,
  },
  {
    slug: "agency-studio",
    name: "Agency Studio",
    description: "A creative agency site: sticky nav, bold hero, services grid, selected-work gallery, team avatars, client logos, testimonial, contact CTA, footer.",
    kind: "website",
    category: "agency-studio",
    pages: "single",
    tags: ["website", "agency-studio"],
    components: ["button", "badge", "input", "textarea", "label", "separator", "avatar"],
    order: 3,
  },
  {
    slug: "personal-portfolio",
    name: "Personal Portfolio",
    description: "A developer/designer portfolio: hero intro with avatar, featured projects cards, about, skills badges, experience timeline, contact, footer.",
    kind: "website",
    category: "portfolio",
    pages: "single",
    tags: ["website", "portfolio"],
    components: ["button", "card", "badge", "input", "label", "textarea", "separator", "avatar"],
    order: 4,
  },
  {
    slug: "ecommerce-store",
    name: "E-commerce Store",
    description: "A storefront home: nav with cart, hero promo, category tiles, featured product grid with prices and add-to-cart, reviews, newsletter, footer.",
    kind: "website",
    category: "ecommerce",
    pages: "single",
    tags: ["website", "ecommerce"],
    components: ["button", "card", "badge", "input", "avatar", "separator"],
    order: 5,
  },
  {
    slug: "startup-launch",
    name: "Startup Launch",
    description: "A pre-launch startup page: hero with waitlist email input, problem vs solution, feature highlights, how-it-works steps, founders, FAQ accordion, footer.",
    kind: "website",
    category: "startup-launch",
    pages: "single",
    tags: ["website", "startup-launch"],
    components: ["button", "card", "badge", "input", "separator", "avatar", "accordion"],
    order: 6,
  },
  {
    slug: "corporate-business",
    name: "Corporate Business",
    description: "A corporate site: nav, hero, services cards, stats band, leadership team, case study highlight, partner logos, contact CTA, footer.",
    kind: "website",
    category: "corporate",
    pages: "single",
    tags: ["website", "corporate"],
    components: ["button", "card", "badge", "input", "label", "textarea", "separator", "avatar"],
    order: 7,
  },
  {
    slug: "blog-magazine",
    name: "Blog Magazine",
    description: "A magazine/blog home: nav with categories, featured hero article, latest posts grid with tags and author avatars, category sidebar, newsletter, footer.",
    kind: "website",
    category: "blog-publishing",
    pages: "single",
    tags: ["website", "blog-publishing"],
    components: ["button", "card", "badge", "input", "separator", "avatar"],
    order: 8,
  },
  {
    slug: "event-conference",
    name: "Event Conference",
    description: "A conference landing: hero with date/location and register CTA, speakers grid, agenda/schedule list with tabs for days, ticket tiers, sponsors, footer.",
    kind: "website",
    category: "events",
    pages: "single",
    tags: ["website", "events"],
    components: ["button", "card", "badge", "input", "separator", "avatar", "tabs"],
    order: 9,
  },
  {
    slug: "course-landing",
    name: "Course Landing",
    description: "An online course landing: hero with enroll CTA, what-you-learn checklist, curriculum accordion, instructor bio, student testimonials, pricing, FAQ, footer.",
    kind: "website",
    category: "education",
    pages: "single",
    tags: ["website", "education"],
    components: ["button", "card", "badge", "separator", "avatar", "accordion"],
    order: 10,
  },
  {
    slug: "crm-dashboard",
    name: "CRM Dashboard",
    description: "An interactive CRM dashboard: left sidebar nav, topbar with search, KPI cards (pipeline value, deals, win rate), a deals table with stage badges, tasks list with checkboxes, recent activity. Use useState for a stage filter that filters the deals table.",
    kind: "saas",
    category: "crm",
    pages: "single",
    tags: ["saas", "crm"],
    components: ["button", "card", "badge", "input", "separator", "avatar", "table", "checkbox"],
    order: 11,
  },
  {
    slug: "project-dashboard",
    name: "Project Dashboard",
    description: "An interactive project management dashboard: sidebar nav, topbar, KPI cards, a kanban-style 3-column board (To do / In progress / Done) of task cards, a progress bar per project, team avatars. Use useState to switch a tab between My tasks / Team.",
    kind: "saas",
    category: "project",
    pages: "single",
    tags: ["saas", "project"],
    components: ["button", "card", "badge", "input", "progress", "avatar"],
    order: 12,
  },
  {
    slug: "product-feature-page",
    name: "Product Feature Page",
    description: "A deep-dive feature page for one product capability: nav, hero with a product mock placeholder, alternating feature rows (text + visual block), a metrics band, integration logos, and a CTA.",
    kind: "website",
    category: "saas-software",
    pages: "single",
    tags: ["website", "saas-software"],
    components: ["button", "badge", "separator"],
    order: 13,
  },
  {
    slug: "saas-pricing-page",
    name: "SaaS Pricing Page",
    description: "A dedicated pricing page: nav, headline, a monthly/annual toggle (useState) that switches prices, three pricing tiers, a feature comparison table, and an FAQ accordion.",
    kind: "website",
    category: "saas-software",
    pages: "single",
    tags: ["website", "saas-software"],
    components: ["button", "card", "badge", "switch", "label", "separator", "table", "accordion"],
    order: 14,
  },
  {
    slug: "app-landing",
    name: "Mobile App Landing",
    description: "A mobile app landing page: nav, hero with phone-mock placeholder and app-store badges, feature highlights with icons, screenshots carousel placeholder, ratings, download CTA.",
    kind: "website",
    category: "marketing-landing",
    pages: "single",
    tags: ["website", "marketing-landing"],
    components: ["button", "card", "badge", "separator"],
    order: 15,
  },
  {
    slug: "newsletter-landing",
    name: "Newsletter Landing",
    description: "A newsletter/creator landing: hero with email subscribe input, what-you-get bullets, recent issues list, author bio, testimonials, subscribe CTA.",
    kind: "website",
    category: "marketing-landing",
    pages: "single",
    tags: ["website", "marketing-landing"],
    components: ["button", "card", "badge", "input", "separator", "avatar"],
    order: 16,
  },
  {
    slug: "design-studio",
    name: "Design Studio",
    description: "A minimalist design studio: large type hero, services list, a 2-column case-study grid, an awards/recognition row, process steps, contact.",
    kind: "website",
    category: "agency-studio",
    pages: "single",
    tags: ["website", "agency-studio"],
    components: ["button", "badge", "input", "label", "textarea", "separator"],
    order: 17,
  },
  {
    slug: "photographer-portfolio",
    name: "Photographer Portfolio",
    description: "A photographer portfolio: full-bleed hero, a masonry-ish gallery grid of placeholder image blocks, about, services/packages, contact form.",
    kind: "website",
    category: "portfolio",
    pages: "single",
    tags: ["website", "portfolio"],
    components: ["button", "card", "badge", "input", "label", "textarea", "separator"],
    order: 18,
  },
  {
    slug: "product-detail",
    name: "Product Detail",
    description: "An e-commerce product detail page: breadcrumb, gallery thumbnails + main image placeholder, title/price/rating, variant selectors (size buttons with useState), add-to-cart, accordion details, related products grid.",
    kind: "website",
    category: "ecommerce",
    pages: "single",
    tags: ["website", "ecommerce"],
    components: ["button", "card", "badge", "separator", "accordion"],
    order: 19,
  },
  {
    slug: "fashion-store",
    name: "Fashion Store",
    description: "A fashion storefront: nav with cart, editorial hero, collection tiles, product grid with price and quick-add, lookbook band, newsletter, footer.",
    kind: "website",
    category: "ecommerce",
    pages: "single",
    tags: ["website", "ecommerce"],
    components: ["button", "card", "badge", "input", "separator"],
    order: 20,
  },
  {
    slug: "coming-soon",
    name: "Coming Soon",
    description: "A coming-soon / waitlist page: centered logo, big headline, a countdown row (static numbers), email waitlist input with success state via useState, social proof count, footer.",
    kind: "website",
    category: "startup-launch",
    pages: "single",
    tags: ["website", "startup-launch"],
    components: ["button", "input", "label", "badge", "separator", "avatar"],
    order: 21,
  },
  {
    slug: "consulting-firm",
    name: "Consulting Firm",
    description: "A consulting firm site: nav, authoritative hero, services cards, industries grid, results/stats band, client logos, leadership team, contact CTA.",
    kind: "website",
    category: "corporate",
    pages: "single",
    tags: ["website", "corporate"],
    components: ["button", "card", "badge", "input", "label", "textarea", "separator", "avatar"],
    order: 22,
  },
  {
    slug: "article-page",
    name: "Article Page",
    description: "A blog article reading page: nav, article header with title/author/date/reading-time, a prose body with headings, blockquote, list and an inline code line, author card, related posts, newsletter.",
    kind: "website",
    category: "blog-publishing",
    pages: "single",
    tags: ["website", "blog-publishing"],
    components: ["button", "card", "badge", "input", "separator", "avatar"],
    order: 23,
  },
  {
    slug: "webinar-landing",
    name: "Webinar Landing",
    description: "A webinar registration landing: hero with date/time and register form, what-you-learn list, speaker cards, agenda, testimonials, register CTA.",
    kind: "website",
    category: "events",
    pages: "single",
    tags: ["website", "events"],
    components: ["button", "card", "badge", "input", "label", "checkbox", "separator", "avatar"],
    order: 24,
  },
  {
    slug: "bootcamp-landing",
    name: "Bootcamp Landing",
    description: "A coding bootcamp landing: hero with apply CTA, outcomes stats, curriculum accordion by week, instructors, tuition/financing cards, student outcomes, FAQ.",
    kind: "website",
    category: "education",
    pages: "single",
    tags: ["website", "education"],
    components: ["button", "card", "badge", "separator", "avatar", "accordion"],
    order: 25,
  },
  {
    slug: "help-center",
    name: "Help Center",
    description: "A help center / docs home: nav, big search input hero, category cards grid (Getting started, Billing, API, etc.), popular articles list, contact-support CTA.",
    kind: "website",
    category: "education",
    pages: "single",
    tags: ["website", "education"],
    components: ["button", "card", "badge", "input"],
    order: 26,
  },
  {
    slug: "finance-dashboard",
    name: "Finance Dashboard",
    description: "An interactive finance dashboard: sidebar nav, topbar, KPI cards (balance, income, expenses, savings rate), a bar/line chart built from divs, a transactions table with category badges, and a budget progress list. useState range switcher updates KPIs.",
    kind: "saas",
    category: "finance",
    pages: "single",
    tags: ["saas", "finance"],
    components: ["button", "card", "badge", "input", "avatar", "table", "progress"],
    order: 27,
  },
  {
    slug: "ai-chat",
    name: "AI Chat",
    description: "An interactive AI chat app: left conversations sidebar, main chat thread with alternating user/assistant bubbles from seeded data, a textarea composer with send button that appends a user message and a canned assistant reply via useState, model selector chips.",
    kind: "saas",
    category: "ai",
    pages: "single",
    tags: ["saas", "ai"],
    components: ["button", "avatar", "badge", "input", "textarea", "separator"],
    order: 28,
  },
  {
    slug: "account-settings",
    name: "Account Settings",
    description: "An interactive multi-section settings area: left settings nav (Profile, Account, Notifications, Billing, Team) switched via useState, each section rendering a real form with inputs/switches; a profile section with avatar + fields, a notifications section with switch rows, a billing section with plan card and invoices table.",
    kind: "saas",
    category: "full-product",
    pages: "multi",
    tags: ["saas", "full-product"],
    components: ["button", "card", "badge", "input", "label", "textarea", "separator", "avatar", "switch", "table"],
    order: 29,
  },
  {
    slug: "web-analytics",
    name: "Web Analytics",
    description: "An interactive web-analytics dashboard distinct from a generic one: realtime visitors number, a sources tab group (useState) switching a table of referrers, a world/regions list with progress bars, top pages, and a sessions sparkline from divs.",
    kind: "saas",
    category: "analytics",
    pages: "single",
    tags: ["saas", "analytics"],
    components: ["button", "card", "badge", "separator", "progress", "table"],
    order: 30,
  },
  {
    slug: "contacts-crm",
    name: "Contacts CRM",
    description: "An interactive contacts management view: sidebar, topbar with search, a contacts table with avatar, company, status badges, and a useState search box that filters rows; a right detail drawer-like panel showing the selected contact; segment filter tabs.",
    kind: "saas",
    category: "crm",
    pages: "single",
    tags: ["saas", "crm"],
    components: ["avatar", "badge", "button", "input", "separator", "table"],
    order: 31,
  },
  {
    slug: "kanban-app",
    name: "Kanban App",
    description: "An interactive kanban board app: topbar with project switcher, four columns (Backlog, To do, In progress, Done) of task cards with labels/assignee avatars/counts, a useState filter by assignee, and a board/list view toggle.",
    kind: "saas",
    category: "project",
    pages: "single",
    tags: ["saas", "project"],
    components: ["button", "badge", "input", "avatar"],
    order: 32,
  },
]

export function getTemplate(slug: string): TemplateMeta | null {
  return TEMPLATES.find((t) => t.slug === slug) ?? null
}
