"use client"

import * as React from "react"
import {
  ArrowDownRight,
  ArrowUpRight,
  ChevronRight,
  DollarSign,
  Download,
  Filter,
  Repeat,
  Share2,
  Sparkles,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Zap,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Progress } from "@/components/ui/progress"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"

type StageKey = "acquisition" | "activation" | "retention" | "referral" | "revenue"

type Stage = {
  key: StageKey
  label: string
  icon: React.ComponentType<{ className?: string }>
  kpi: string
  kpiLabel: string
  delta: number
  blurb: string
  chart: number[]
  table: { label: string; value: string; share: number; trend: number }[]
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"]

const STAGES: Stage[] = [
  {
    key: "acquisition",
    label: "Acquisition",
    icon: UserPlus,
    kpi: "48.2K",
    kpiLabel: "New visitors",
    delta: 12.4,
    blurb: "Top-of-funnel traffic reaching the product for the first time.",
    chart: [38, 44, 41, 52, 57, 49, 63, 71],
    table: [
      { label: "Organic search", value: "18,420", share: 38, trend: 9.1 },
      { label: "Paid social", value: "11,980", share: 25, trend: 14.6 },
      { label: "Direct", value: "8,640", share: 18, trend: 2.3 },
      { label: "Email", value: "5,210", share: 11, trend: -3.4 },
      { label: "Partnerships", value: "3,950", share: 8, trend: 21.7 },
    ],
  },
  {
    key: "activation",
    label: "Activation",
    icon: Zap,
    kpi: "62.8%",
    kpiLabel: "Activation rate",
    delta: 4.7,
    blurb: "Signups that reach their first aha moment within 24 hours.",
    chart: [51, 54, 53, 58, 60, 59, 61, 63],
    table: [
      { label: "Completed onboarding", value: "9,310", share: 41, trend: 6.2 },
      { label: "Created first project", value: "6,740", share: 30, trend: 8.9 },
      { label: "Invited a teammate", value: "3,820", share: 17, trend: 11.4 },
      { label: "Connected an integration", value: "2,710", share: 12, trend: -1.8 },
    ],
  },
  {
    key: "retention",
    label: "Retention",
    icon: Repeat,
    kpi: "84.1%",
    kpiLabel: "30-day retention",
    delta: 2.1,
    blurb: "Activated users who remain active after their first month.",
    chart: [70, 72, 74, 73, 78, 80, 82, 84],
    table: [
      { label: "Daily active core", value: "12,040", share: 44, trend: 3.5 },
      { label: "Weekly returners", value: "8,330", share: 30, trend: 1.9 },
      { label: "Reactivated", value: "4,120", share: 15, trend: 18.2 },
      { label: "At-risk (dormant 14d)", value: "2,980", share: 11, trend: -6.7 },
    ],
  },
  {
    key: "referral",
    label: "Referral",
    icon: Share2,
    kpi: "1.38",
    kpiLabel: "Viral coefficient",
    delta: 7.9,
    blurb: "Invites and shares generated by your existing active users.",
    chart: [28, 31, 35, 33, 39, 42, 46, 51],
    table: [
      { label: "Invite links sent", value: "7,460", share: 36, trend: 12.8 },
      { label: "Shared dashboards", value: "5,210", share: 25, trend: 9.3 },
      { label: "Reward redemptions", value: "4,030", share: 20, trend: 22.5 },
      { label: "Affiliate signups", value: "3,890", share: 19, trend: 5.1 },
    ],
  },
  {
    key: "revenue",
    label: "Revenue",
    icon: DollarSign,
    kpi: "$214K",
    kpiLabel: "Monthly recurring",
    delta: 9.6,
    blurb: "Recurring revenue contributed across all active plans.",
    chart: [120, 134, 142, 151, 168, 179, 195, 214],
    table: [
      { label: "Pro plan", value: "$118,400", share: 55, trend: 8.4 },
      { label: "Team plan", value: "$61,200", share: 29, trend: 13.1 },
      { label: "Enterprise", value: "$28,900", share: 13, trend: 19.6 },
      { label: "Add-ons", value: "$5,500", share: 3, trend: -2.2 },
    ],
  },
]

const FUNNEL = [
  { label: "Acquisition", value: 48200, pct: 100 },
  { label: "Activation", value: 30270, pct: 63 },
  { label: "Retention", value: 25450, pct: 53 },
  { label: "Referral", value: 11340, pct: 24 },
  { label: "Revenue", value: 6820, pct: 14 },
]

const CHANNELS = [
  { name: "Organic", initials: "OR", spend: "$0", cac: "$0", roi: "—", rev: "$74.1K", weight: 92 },
  { name: "Paid Social", initials: "PS", spend: "$18.4K", cac: "$41", roi: "3.2x", rev: "$59.0K", weight: 71 },
  { name: "Lifecycle Email", initials: "LE", spend: "$2.1K", cac: "$6", roi: "9.7x", rev: "$28.6K", weight: 58 },
  { name: "Referral Program", initials: "RP", spend: "$6.3K", cac: "$12", roi: "5.4x", rev: "$34.2K", weight: 64 },
]

function formatCount(n: number) {
  return n.toLocaleString("en-US")
}

function Delta({ value }: { value: number }) {
  const positive = value >= 0
  return (
    <span
      className={cn(
        "inline-flex items-center gap-0.5 text-xs font-medium",
        positive ? "text-primary" : "text-destructive"
      )}
    >
      {positive ? (
        <ArrowUpRight className="h-3.5 w-3.5" />
      ) : (
        <ArrowDownRight className="h-3.5 w-3.5" />
      )}
      {Math.abs(value).toFixed(1)}%
    </span>
  )
}

export default function GrowthDashboard() {
  const [active, setActive] = React.useState<StageKey>("acquisition")
  const stage = STAGES.find((s) => s.key === active) ?? STAGES[0]
  const chartMax = Math.max(...stage.chart)

  return (
    <div className="flex min-h-full flex-col bg-background text-foreground">
      <header className="sticky top-0 z-20 border-b bg-background/80 backdrop-blur">
        <div className="mx-auto flex w-full max-w-7xl items-center gap-4 px-4 py-3 sm:px-6">
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <TrendingUp className="h-5 w-5" />
            </div>
            <div className="leading-tight">
              <p className="text-sm font-semibold">Northstar</p>
              <p className="text-xs text-muted-foreground">Growth analytics</p>
            </div>
          </div>
          <nav className="ml-6 hidden items-center gap-1 md:flex">
            <Button variant="secondary" size="sm">
              Overview
            </Button>
            <Button variant="ghost" size="sm">
              Cohorts
            </Button>
            <Button variant="ghost" size="sm">
              Experiments
            </Button>
            <Button variant="ghost" size="sm">
              Reports
            </Button>
          </nav>
          <div className="ml-auto flex items-center gap-2">
            <Button variant="outline" size="sm" className="hidden sm:inline-flex">
              <Filter className="h-4 w-4" />
              Last 8 months
            </Button>
            <Button size="sm">
              <Download className="h-4 w-4" />
              Export
            </Button>
            <Avatar className="h-8 w-8">
              <AvatarFallback>NK</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-7xl flex-1 px-4 py-6 sm:px-6 lg:py-8">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-semibold tracking-tight">
                AARRR Growth Overview
              </h1>
              <Badge variant="secondary" className="gap-1">
                <Sparkles className="h-3 w-3" />
                Live
              </Badge>
            </div>
            <p className="mt-1 text-sm text-muted-foreground">
              Pirate-metrics across the full lifecycle. Switch a stage to drill into its channels.
            </p>
          </div>
          <Badge variant="outline" className="w-fit gap-1">
            <Target className="h-3 w-3 text-primary" />
            Q3 target on track
          </Badge>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {STAGES.map((s) => {
            const isActive = s.key === active
            const Icon = s.icon
            return (
              <button
                key={s.key}
                type="button"
                onClick={() => setActive(s.key)}
                aria-pressed={isActive}
                className={cn(
                  "rounded-xl border p-4 text-left transition-colors",
                  isActive
                    ? "border-primary bg-primary/10 ring-1 ring-primary"
                    : "bg-card hover:bg-accent"
                )}
              >
                <div className="flex items-center justify-between">
                  <span
                    className={cn(
                      "flex h-8 w-8 items-center justify-center rounded-lg",
                      isActive
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted text-muted-foreground"
                    )}
                  >
                    <Icon className="h-4 w-4" />
                  </span>
                  <Delta value={s.delta} />
                </div>
                <p className="mt-3 text-2xl font-semibold tracking-tight">{s.kpi}</p>
                <p className="text-xs text-muted-foreground">{s.label}</p>
              </button>
            )
          })}
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-3">
          <Card className="lg:col-span-2">
            <CardHeader>
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2">
                    <stage.icon className="h-4 w-4 text-primary" />
                    {stage.label} trend
                  </CardTitle>
                  <CardDescription>{stage.blurb}</CardDescription>
                </div>
                <Tabs value={active} onValueChange={(v) => setActive(v as StageKey)}>
                  <TabsList>
                    {STAGES.map((s) => (
                      <TabsTrigger key={s.key} value={s.key} className="text-xs">
                        {s.label}
                      </TabsTrigger>
                    ))}
                  </TabsList>
                </Tabs>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-semibold tracking-tight">
                  {stage.kpi}
                </span>
                <span className="text-sm text-muted-foreground">{stage.kpiLabel}</span>
                <Delta value={stage.delta} />
              </div>
              <div className="mt-6 flex h-48 items-end gap-2 sm:gap-3">
                {stage.chart.map((v, i) => (
                  <div
                    key={MONTHS[i]}
                    className="group flex flex-1 flex-col items-center justify-end gap-2"
                  >
                    <div className="flex w-full items-end justify-center">
                      <div
                        className={cn(
                          "w-full rounded-t-md transition-all",
                          i === stage.chart.length - 1
                            ? "bg-primary"
                            : "bg-primary/30 group-hover:bg-primary/50"
                        )}
                        style={{ height: `${(v / chartMax) * 160}px` }}
                      />
                    </div>
                    <span className="text-[11px] text-muted-foreground">{MONTHS[i]}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Funnel overview</CardTitle>
              <CardDescription>Users progressing through each stage.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {FUNNEL.map((f, i) => {
                const isCurrent = STAGES[i]?.key === active
                return (
                  <div key={f.label}>
                    <div className="flex items-center justify-between text-sm">
                      <span
                        className={cn(
                          "font-medium",
                          isCurrent && "text-primary"
                        )}
                      >
                        {f.label}
                      </span>
                      <span className="tabular-nums text-muted-foreground">
                        {formatCount(f.value)}
                        <span className="ml-2 text-xs">{f.pct}%</span>
                      </span>
                    </div>
                    <Progress value={f.pct} className="mt-2 h-2" />
                  </div>
                )
              })}
            </CardContent>
          </Card>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-3">
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>{stage.label} breakdown</CardTitle>
              <CardDescription>
                Sources contributing to {stage.label.toLowerCase()} this period.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Source</TableHead>
                    <TableHead className="text-right">Volume</TableHead>
                    <TableHead className="w-[160px]">Share</TableHead>
                    <TableHead className="text-right">Trend</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {stage.table.map((row) => (
                    <TableRow key={row.label}>
                      <TableCell className="font-medium">{row.label}</TableCell>
                      <TableCell className="text-right tabular-nums">
                        {row.value}
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Progress value={row.share} className="h-1.5" />
                          <span className="w-9 text-right text-xs tabular-nums text-muted-foreground">
                            {row.share}%
                          </span>
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                        <Delta value={row.trend} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="h-4 w-4 text-primary" />
                Channels
              </CardTitle>
              <CardDescription>Efficiency by acquisition channel.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {CHANNELS.map((c) => (
                <div key={c.name} className="rounded-lg border bg-muted/30 p-3">
                  <div className="flex items-center gap-3">
                    <Avatar className="h-8 w-8">
                      <AvatarFallback className="text-xs">{c.initials}</AvatarFallback>
                    </Avatar>
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-medium">{c.name}</p>
                      <p className="text-xs text-muted-foreground">
                        CAC {c.cac} · ROI {c.roi}
                      </p>
                    </div>
                    <span className="text-sm font-semibold tabular-nums">{c.rev}</span>
                  </div>
                  <Progress value={c.weight} className="mt-3 h-1.5" />
                </div>
              ))}
              <Button variant="ghost" size="sm" className="w-full justify-between">
                View all channels
                <ChevronRight className="h-4 w-4" />
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>

      <footer className="border-t">
        <div className="mx-auto flex w-full max-w-7xl flex-col items-center justify-between gap-2 px-4 py-4 text-xs text-muted-foreground sm:flex-row sm:px-6">
          <p>© 2026 Northstar Analytics. All metrics are illustrative.</p>
          <p>Data refreshed every 15 minutes · Timezone UTC</p>
        </div>
      </footer>
    </div>
  )
}
